---
title: "RWorksheet_Sante#4c.Rmd"
author: "Sharrene Sante"
date: "2023-12-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1
```{r num1}
install.packages("ggplot2")
library(ggplot2)
install.packages("tidyverse")
```

```{r num1a}
data(mpg)
mpg
```

```{r num1b}
#  Which variables from mpg dataset are categorical?

#The variables that are categorical in mpg dataset are manufacturer, model, trans, drv, and fl.
```


```{r num1c}
#Which are continuous variables?

#The continuous variables in the mpg dataset are displ, year, cyl, cty, and hwy.
```

#2
```{r num2}
library(dplyr)
manufacturer_most_models <- mpg %>%
  group_by(manufacturer) %>%
  summarize(number_of_models = n_distinct(model)) %>%
  top_n(1, number_of_models)
model_most_variations <- mpg %>%
  group_by(model) %>%
  summarize(number_of_variations = n_distinct(trans)) %>%
  top_n(1, number_of_variations)
cat("Manufacturer with the most models:", manufacturer_most_models$manufacturer, "\n")
cat("Model with the most variations:", model_most_variations$model, "\n")

```

```{r num2a}
library(dplyr)
unique_models_by_manufacturer <- mpg %>%
  group_by(manufacturer) %>%
  distinct(model)
print(unique_models_by_manufacturer)
```

```{r num2b}
models_per_manufacturer <- table(mpg$manufacturer)

plot(models_per_manufacturer, 
     main = "Number of Models by Manufacturer",
     xlab = "Manufacturer",
     ylab = "Number of Models",
     col = "red",
     ylim = c(0, max(models_per_manufacturer) + 2))

max_manufacturer <- which.max(models_per_manufacturer)
text(max_manufacturer, models_per_manufacturer[max_manufacturer] + 1,
     labels = paste("Max:", max(models_per_manufacturer)),
     col = "blue", pos = 3)

library(ggplot2)

ggplot(data = as.data.frame(models_per_manufacturer), aes(x = Var1, y = Freq)) +
  geom_bar(stat = "identity", fill = "red") +
  labs(title = "Number of Models by Manufacturer",
       x = "Manufacturer",
       y = "Number of Models") +
  geom_text(aes(label = Freq), vjust = -0.3, col = "blue", size = 3) +
  theme_minimal()

```


```{r num2A}
library(ggplot2)
ggplot(mpg, aes(model, manufacturer)) + 
  geom_point()


```


```{r num2B}
library(ggplot2)
ggplot(mpg, aes(model, fill = manufacturer)) + 
  geom_bar(position = "dodge") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

#3
```{r num3}
library(ggplot2)
top_20 <- head(mpg, 20)
ggplot(top_20, aes(model, year)) + 
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```


#4
```{r num4}
library(dplyr)
car_counts <- mpg %>%
  group_by(model) %>%
  summarize(number_of_cars = n())
print(car_counts)
```

```{r num4a}
library(ggplot2)
top_20 <- head(mpg, 20)
ggplot(top_20, aes(x = model, fill = factor(model))) +
  geom_bar() +
  labs(title = "Number of Cars by Model (Top 20 Observations)",
       x = "Car Model",
       y = "Number of Cars") +
  scale_fill_discrete(name = "Car Model") +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```

```{r num4b}
library(ggplot2)
top_20 <- head(mpg, 20)
ggplot(top_20, aes(x = model, fill = factor(model))) +
  geom_bar() +
  labs(title = "Number of Cars by Model (Top 20 Observations)",
       x = "Number of Cars",
       y = "Car Model") +
  scale_fill_discrete(name = "Car Model") +  
  coord_flip() 
```

#5
```{r num5}
library(ggplot2)
ggplot(mpg, aes(x = cyl, y = displ, color = displ)) +
  geom_point() +
  labs(title = "Relationship between No. of Cylinders and Engine Displacement",
       x = "Number of Cylinders",
       y = "Engine Displacement") +
  scale_color_continuous(name = "Engine Displacement")  
```


#5a
```{r num5a}
library(ggplot2)
ggplot(mpg, aes(x = cyl, y = displ, color = displ)) +
  geom_point() +
  labs(title = "Relationship between No. of Cylinders and Engine Displacement",
       x = "Number of Cylinders",
       y = "Engine Displacement") +
  scale_color_continuous(name = "Engine Displacement")
```


#6
```{r num6}
library(ggplot2)
continuous_variable <- mpg$your_continuous_variable
ggplot(mpg, aes(x = displ, y = hwy, color = continuous_variable)) +
  geom_point() +
  labs(title = "Relationship between Engine Displacement and Highway MPG",
       x = "Engine Displacement",
       y = "Highway MPG") +
  scale_color_continuous(name = "Your Continuous Variable")  
```


```{r num6.1}
library(readr)
traffic <- read_csv("traffic.csv")
traffic
```


```{r num6a}
observations <- nrow(traffic)
observations

columns <- ncol(traffic)
columns
```


```{r num6b}
junction1 <- subset(traffic, Junction ==1)
junction1

junction2 <- subset(traffic, Junction ==2)
junction2

junction3 <- subset(traffic, Junction ==3)
junction3

junction4 <- subset(traffic, Junction ==4)
junction4
```



``` {r num6c}
library(ggplot2)

ggplot(traffic, aes(x = seq_along(Junction), y = DateTime, group = Junction, color = factor(Junction))) +
  geom_line() +
  labs(title = "Plots in each Junction",
       x = "Observation",
       y = "Date&Time") +
  scale_color_discrete(name = "Junction")
```


#7
```{r num7} 
library(readxl)
alexa_file <- read_excel("alexa_file.xlsx")
alexa_file
```


``` {r num7a}
observe <- nrow(alexa_file)
observe

column <- ncol (alexa_file)
column
```


``` {r num7b}
library(dplyr)

result <- alexa_file %>%
  group_by(variation) %>%
  summarize(total = n())

print(result)
```


``` {r num7c}
ggplot(alexa_file, aes(x = variation)) +
  geom_bar(fill = "yellow", color = "red") +
  labs(title = "Distribution of Variation",
       y = "Count",
       x = "Variations") +
  coord_flip()
```


``` {r num7d}
ggplot(alexa_file, aes(x = date, y = rating)) +
  geom_line(color= "lightblue") +
  labs (title = "Date and the number of verified reviews",
        x = "Date",
        y = "Rating") +
  coord_flip()
```


``` {r num7e}
ggplot(alexa_file, aes(x = variation, y = rating)) +
  geom_boxplot(fill = "green", color = "black") +
  labs(title = "Relationship Between Variations and Ratings",
       x = "Variations",
       y = "Ratings") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```

