---
title: "RWorksheet_Sante#4b.Rmd"
author: "Sharrene Sante"
date: "2023-11-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1
```{r num1}
vectorA <- c(1,2,3,4,5)
matrixA <- matrix(0,nrow = 5, ncol = 5)
for (i in 1:5){
  for (j in 1:5){
    matrixA[i, j]<- abs(vectorA[i] - vectorA[j])
  }
}

matrixA
```
#2
```{r num2}
num_rows <- 5
for(i in 1:num_rows){
  for(j in 1:i){
    cat("*")
  }
  cat("\n")
}
```
#3
```{r num3}
input.number <- as.numeric(readline("Enter a number to start the Fibonacci sequence: "))
assume.number <- 0
x <- 0
y <- 1
repeat {
  if (x > 500) {
    break
  }
  if (x >= assume.number) {
    cat(x, " ")
  }
  temp <- x + y
  x <- y
  y <- temp
}
cat("\n")

```

#4
```{r num4}
library(readr)
Shoesize <- read_csv("/cloud/project/Rworksheet4/Shoesize.csv", show_col_types = FALSE)
Shoesize
```
```{r num4a}
Shoesize <- read.csv("Shoesize.csv")
Shoesize
size <- Shoesize[c(1:6),]
size
```
```{r num4b}
male_subset <- Shoesize[Shoesize$Gender == "M", c("Shoes.Size", "Height")]
female_subset <- Shoesize[Shoesize$Gender == "F", c("Shoes.Size", "Height")]
male_subset
female_subset
```

```{r num4c}
household <- read.csv("HouseholdData.csv")
household

gender_counts <- table(household$Sex)

plot(1, type = "n", main = "Number of Males and Females in Household Data",
     xlab = "Sex", ylab = "Count", xlim = c(0.2, 2.5), ylim = c(0, max(gender_counts)))

barplot(gender_counts, col = c("red", "skyblue"), add = TRUE)
legend("topright", legend = levels(as.factor(household$Sex)), fill = c("red", "skyblue"))
```



#5
```{r num5}
pie_chart <- c(60, 10, 5, 25)
pie(pie_chart, labels = paste0(pie_chart, "%"), 
    main = "The Monthly Income of Dela Cruz family was spent on the following: ", col = rainbow(length(pie_chart))) 
legend("topleft", legend = c("Food", "Electricity", "Savings", "Miscellaneous"), fill = rainbow(length(pie_chart)))
```


#6
```{r num6}
data<-(iris)
str(iris)
```

```{r num6b}
meanIris<- colMeans(iris[,c("Sepal.Width","Petal.Length","Petal.Width")])
print(meanIris)
```

```{r num6c}
specs<-table(iris$Species)

clors<-c("yellow","skyblue","lightgreen")

pie(specs,labels = paste(names(specs),"\n",
        sprintf("%.1f%%",prop.table(specs)*100)),
    col= clors,
    main= "Species Distribution",
    cex.main = 1.5,
    cex =0.8)
```
```{r num6d}
SetSub <- subset(iris, Species == "setosa")
VersiSub <- subset(iris, Species == "versicolor")
VirgiSub <- subset(iris, Species == "virginica")

cat("Last six rows of Setosa:")
print(tail(SetSub))

cat("Last six rows of Versicolor:")
print(tail(VersiSub))

cat("Last six rows of Virginica:")
print(tail(VirgiSub))

```


```{r num6e}
data(iris)

iris$Species <- as.factor(iris$Species)

plot(iris$Sepal.Length, iris$Sepal.Width,
     pch = as.integer(iris$Species),
     col = iris$Species,
     main = "Iris Dataset",
     sub = "Sepal width and length",
     xlab = "Sepal Length",
     ylab = "Sepal Width"
)
```

```{r num6f}
#The scatterplot shows similarities between the sepal width and length ranging from 5.5 to 7.0
```


```{r num7}
library(readxl)
alexa_file <- read_excel("/cloud/project/Rworksheet4/alexa_file.xlsx")
alexa_file
```
```
